In [ ]:
!python --version

Python 3.7.10


In [ ]:
x = 3.4
print(x)
print(type(x))

3.4
<class 'float'>


In [ ]:
print(x + 1)
print(x - 1)
print(x * 2)
print(x ** 2)

4.4
2.4
6.8
11.559999999999999


In [ ]:
x += 2 # x = x + 2
print(x)
x *= 3 # x = x * 3
print(x)

7.4
22.200000000000003


In [ ]:
t = True
f = False
print(type(t))

<class 'bool'>


In [ ]:
print(True and True)

True


In [ ]:
print(t and f)

False


In [ ]:
print(t or f)

True


In [ ]:
print(not t)

False


In [ ]:
print(2 == 3)

False


In [ ]:
hello = 'hello'
Hello = "Hello"
print(hello, Hello)

hello Hello


In [ ]:
len(hello)
hello = 'hello' + ' everyone'

print(hello, len(hello))

hello everyone 14


In [ ]:
s = 'falooda'
print(s.capitalize())
print(s.upper())
print(s.islower())

Falooda
FALOODA
True


In [ ]:
## Lists

xs = [1, 2.3, True, 'lassi']
print(xs)

[1, 2.3, True, 'lassi']


In [ ]:
xs[-2]

True

In [ ]:
xs.append(s)
print(xs)

[1, 2.3, True, 'lassi', 'falooda']


In [ ]:
nums = list(range(5))
print(nums)

[0, 1, 2, 3, 4]


In [ ]:
print(nums[2:4])
print(nums[1:])
print(nums[:3])


[2, 3]
[1, 2, 3, 4]
[0, 1, 2]


In [ ]:
nums[2:4] = [5,6]
print(nums)

[0, 1, 5, 6, 4]


In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals :
  print(animal + ' tail') 

cat tail
dog tail
monkey tail


In [ ]:
d = {'name' : 'kkr', 'pet' : 'cat', 'cap': 'no'}
print(d['pet'])
d['cap'] = 'yes'
print(d['cap'])

cat
yes


In [ ]:
dataset = {'train': [1,2,3], 'test': [-1, -2, -3]}
dataset['train']

[1, 2, 3]

In [ ]:
birds = {'parrot', 'duck'}
print('parrot' in birds)
print('cat' in birds)

True
False


In [ ]:
birds.add('crow')
print(len(birds))

3


In [ ]:
t = (4, 5)
print(t)

(4, 5)


In [ ]:
t[0] = 8

TypeError: ignored

In [ ]:
l = [1, 2, 3]
t = (1, 2, 3)

In [ ]:
l[0] = 5
print(l)

[5, 2, 3]


In [ ]:
t[0] = 5
print(t)

TypeError: ignored

In [ ]:
ryt = (1, 'a')
print(ryt)

(1, 'a')


In [ ]:
!python --version

Python 3.7.10


In [ ]:
for bird in birds:
  print(bird)
print('swan')

crow
duck
parrot
swan


In [ ]:
def sign(x):
  if x > 0 :
    return 'positive'
  elif x < 0 :
    return 'negative'
  else :
    return 'zero'

for a in [-3, 0, 4]:
  print(sign(a))  

negative
zero
positive


In [ ]:
def my_random(x):
  if x > 0 :
    return x ** 3
  elif x < 0 :
    return x * -5
  else :
    return x + 1

for a in [-3, 0, 4]:
  print(my_random(a)) 

15
1
64


In [ ]:
l = [-3, 0, 4]
for i in range(3):
  a = l[i]
  print(my_random(a))

15
1
64


In [ ]:
x = 0
while x < 3 :
  x += 1
  print(x)

1
2
3


In [ ]:
#include math.h
import numpy as np


In [ ]:
l = [1, 'a']
a = np.array(l)
print(a)

['1' 'a']


In [ ]:
a = np.array([1, 2, 3])
print(a)
print(type(a), a.shape)

[1 2 3]
<class 'numpy.ndarray'> (3,)


In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
print(a[0, 1])

2


In [ ]:
id = np.eye(4)
print(id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
zero_m = np.zeros([2,3])
print(zero_m)
zero_m[1,2] = 1
print(zero_m)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 1.]]


In [ ]:
full_m = np.full([3, 4], 5)
print(full_m)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
rand_m = np.random.rand(2, 4)
print(rand_m)

[[0.05277953 0.08796004 0.67633135 0.88388428]
 [0.25655889 0.7153442  0.90438128 0.2262967 ]]


In [ ]:
rand_m = np.random.randint(0, 4, size = (4,3))
print(rand_m)

[[1 2 3]
 [2 0 0]
 [3 0 0]
 [3 2 0]]


In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
b = a[:2, 1:] # first two rows and last two columns
print(b)

[[2 3]
 [5 6]]


In [ ]:
c = a[0, :2]
print(c)
d = a[1, 1:]
print(d)

[1 2]
[5 6]


In [ ]:
e = np.array([c, d])
print(e)

[[1 2]
 [5 6]]


In [ ]:
a = np.random.randint(0, 10, size = (4,5))
print(a)

[[8 7 6 3 5]
 [3 0 5 5 1]
 [5 9 5 3 7]
 [6 1 6 2 8]]


In [ ]:
b = a[:, -1].reshape(-1, 1)
print(b)

[[5]
 [1]
 [7]
 [8]]


In [ ]:
idx = (a > 3)
print(idx)

[[ True  True  True False  True]
 [False False  True  True False]
 [ True  True  True False  True]
 [ True False  True False  True]]


In [ ]:
a[idx]

array([8, 7, 6, 5, 5, 5, 5, 9, 5, 7, 6, 6, 8])

In [ ]:
a[a <= 3] = 0
print(a)

[[8 7 6 0 5]
 [0 0 5 5 0]
 [5 9 5 0 7]
 [6 0 6 0 8]]


In [ ]:
for i in range(4):
  for j in range(5):
    val = a[i, j]
    if val > 6:
      a[i, j] = -1

print(a)

[[-1 -1  6  0  5]
 [ 0  0  5  5  0]
 [ 5 -1  5  0 -1]
 [ 6  0  6  0 -1]]


In [ ]:
b = np.random.rand(3, 4)
print(b)

[[0.49463548 0.37290898 0.87406189 0.92758524]
 [0.41075643 0.50311445 0.45814236 0.52609801]
 [0.27762687 0.84355779 0.44248947 0.52062776]]


In [ ]:
c = b.reshape([-1, 2])
print(c)

[[0.49463548 0.37290898]
 [0.87406189 0.92758524]
 [0.41075643 0.50311445]
 [0.45814236 0.52609801]
 [0.27762687 0.84355779]
 [0.44248947 0.52062776]]


In [ ]:
a = np.random.randint(-4, 20, (5,6))
print(a)

[[ 0 16 -1  6 15  5]
 [ 5  9 10 13 15  4]
 [ 3 17  7  5 17 13]
 [ 3 19 15 16 17 -1]
 [10 17  6 16 -4 -4]]


In [ ]:
a[a[:,  4:] < 0] = 0
print(a)

IndexError: ignored

In [ ]:
b = a[:,  4:]
print(b)
b[b < 0] = 0
print(b)

[[15  5]
 [15  4]
 [17 13]
 [17 -1]
 [-4 -4]]
[[15  5]
 [15  4]
 [17 13]
 [17  0]
 [ 0  0]]


In [ ]:
a[:, 4:] = b
print(a)

[[ 0 16 -1  6 15  5]
 [ 5  9 10 13 15  4]
 [ 3 17  7  5 17 13]
 [ 3 19 15 16 17  0]
 [10 17  6 16  0  0]]


In [ ]:
a[:, 4:][a[:, 4:] > 15] = -1
print(a)

[[ 0 16 -1  6 15  5]
 [ 5  9 10 13 15  4]
 [ 3 17  7  5 -1 13]
 [ 3 19 15 16 -1  0]
 [10 17  6 16  0  0]]


In [ ]:
print(a[:, 4:] > 15)

[[False False]
 [False False]
 [False False]
 [False False]
 [False False]]
